services:
  postgres:
    image: postgres:alpine
    container_name: code-challenge-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - code-challenge-volume:/var/lib/postgresql/data
    networks:
      - code-challenge-network
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build: 
      args:
        - DATABASE_URL
      context: .
      dockerfile: Dockerfile
    container_name: code-challenge-backend
    networks:
      - code-challenge-network
    ports:
      - 3000:3000
    profiles:
      - app
    depends_on:
      - postgres
    environment:
      - PORT=3000

networks:
  code-challenge-network:
    driver: bridge

volumes:
  code-challenge-volume:
    driver: local